apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: pia
  name: brreg-oppdaterer
  namespace: pia
spec:
  image: {{ image }}
  schedule: "0 19 * * *" # Kl 19 hver dag
  accessPolicy:
    outbound:
      external:
        - host: "{{brreg-api-host}}"
  kafka:
    pool: {{kafka-pool}}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  env:
    - name: ANTALL_DAGER_SIDEN_OPPDATERING
      value: "2"
    - name: BRREG_API_BASE_URL
      value: "{{brreg-api-base-url}}"
