apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: pia
  name: brreg-alle-virksomheter
  namespace: pia
spec:
  image: {{ image }}
  accessPolicy:
    outbound:
      external:
        - host: data.brreg.no
  kafka:
    pool: nav-dev # nav-dev / nav-prod
  env:
    - name: LAST_NED_ALLE_VIRKSOMHETER
      value: "true"
